"""tickets table

Revision ID: 67e34ff83c4e
Revises: 
Create Date: 2024-02-19 12:55:47.639590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e34ff83c4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_name'))
        batch_op.drop_index(batch_op.f('ix_ticket_message'))
        batch_op.drop_index(batch_op.f('ix_ticket_email'))

    op.drop_table('ticket')
    # ### end Alembic commands ###
